### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by jaycliff**
turned a few function statements to function expressions, because the function names are already declared at the topmost var statement (komodo edit complains about redeclared functions). Changed 'opera' to just 'o', etc.

### CODE REVIEW

**Comment by notator** [comment]
There's a problem with this merge.

An exception is now thrown in my code because requestMIDIAccess is undefined when calling 

```
navigator.requestMIDIAccess().then(onSuccessCallback, onErrorCallback);
```

I got round this by moving the lines

```
    //init: create plugin
    if(!window.navigator.requestMIDIAccess)
    {
        window.navigator.requestMIDIAccess = _requestMIDIAccess;
        if(!window.navigator.getMIDIAccess)
            window.navigator.getMIDIAccess = _getMIDIAccess;
    }
```

from line 21 down to the end of their block (where _requestMIDIAccess has been defined).

Strangely, _getMIDIAccess is declared but never defined...

best,
James

**Comment by cwilso** [comment]
Fixed.

_getMIDIAccess was an old version of requestMIDIAccess that threw a warning.  I got rid of it when I cleaned up, but forgot the hookup.

**Comment by notator** [comment]
You got rid of the hookup, but _getMIDIAccess is still declared (line 19).

**Comment by cwilso** [comment]
So I did.  Thanks.

**Pull request merged**
