### PR TITLE
Introduced delayed initialization

### PR DESCRIPTION
**Pull request by bjornm**
since the shim no longer works in Chrome, maybe due to async plugin initialization.

### CODE REVIEW

**Comment by jeremyfa** [comment]
I experienced the issue on Chrome too. The delayed initialization seems to fix it for me.

**Comment by cwilso** [comment]
If you're on Chrome, why aren't you just turning on the #enable-web-midi flag?

**Comment by jeremyfa** [comment]
Yes, it is definitely an option, but I still think it is nice to keep the Jazz based implementation working, at least until Chrome doesn't need us to set the flag manually.

**Comment by bjornm** [comment]
I'd love to switch - does web midi api auto detect devices being plugged in / out nowadays? Win vs Mac vs Chrome OS?

**Comment by cwilso** [comment]
It does not yet support live plugging, no.  It is supported across Mac, Win, ChromeOS, Linux and Android, though.

**Pull request merged**
